const STORAGE_KEY = "impact-links-demo-v1";
const plans = { monthly: { label: "Monthly", price: 12, renewalDays: 30 }, yearly: { label: "Yearly", price: 120, renewalDays: 365 } };
const $ = (s) => document.querySelector(s);
const $$ = (s) => Array.from(document.querySelectorAll(s));

const demoData = {
  currentUserId: null,
  drawMode: "random",
  jackpotRollover: 180,
  invoices: [],
  draws: [],
  notifications: [],
  charities: [
    { id: "c1", name: "Bright Futures Trust", cause: "youth", description: "Mentoring, education grants, and safe community spaces for young people.", event: "Summer skills day - 18 June" },
    { id: "c2", name: "Care Circle Foundation", cause: "health", description: "Practical support for families navigating long-term treatment journeys.", event: "Wellbeing fundraiser - 09 July" },
    { id: "c3", name: "Local Roots Network", cause: "community", description: "Neighbourhood projects, food access, and volunteer-led campaigns.", event: "Community impact brunch - 27 May" }
  ],
  users: [
    { id: "u1", role: "subscriber", name: "Aarav Sharma", email: "member@impactlinks.test", password: "member123", plan: "monthly", subscriptionStatus: "active", renewalDate: addDays(new Date(), 18), charityId: "c1", charityPercent: 15, totalWon: 0, payoutStatus: "pending", proofStatus: "pending", drawsEntered: 3, scores: [{ date: "2026-04-26", value: 34 }, { date: "2026-04-19", value: 28 }, { date: "2026-04-12", value: 41 }, { date: "2026-04-05", value: 22 }, { date: "2026-03-29", value: 31 }], activity: ["Welcome email sent", "April draw entry confirmed"] },
    { id: "u2", role: "subscriber", name: "Maya Patel", email: "maya@impactlinks.test", password: "member123", plan: "yearly", subscriptionStatus: "active", renewalDate: addDays(new Date(), 210), charityId: "c2", charityPercent: 20, totalWon: 80, payoutStatus: "paid", proofStatus: "approved", drawsEntered: 7, scores: [{ date: "2026-04-25", value: 18 }, { date: "2026-04-20", value: 34 }, { date: "2026-04-11", value: 41 }, { date: "2026-04-01", value: 29 }, { date: "2026-03-21", value: 30 }], activity: ["Winner proof approved", "Payout marked paid"] },
    { id: "admin", role: "admin", name: "Digital Heroes Admin", email: "admin@impactlinks.test", password: "admin123", activity: [] }
  ],
  winners: [{ id: "w1", userId: "u2", tier: "3-match", amount: 80, proofStatus: "approved", paymentStatus: "paid" }]
};

let state = loadState();
let editingScoreDate = null;
let lastSimulation = null;
let checkoutPlan = "monthly";

document.addEventListener("DOMContentLoaded", () => { bindEvents(); render(); });

function bindEvents() {
  $("#loginBtn").addEventListener("click", openAuth);
  $("#heroSubscribeBtn").addEventListener("click", openAuth);
  $("#heroDemoBtn").addEventListener("click", () => loginDemo("member"));
  $("#resetDemoBtn").addEventListener("click", resetDemo);
  $$("[data-open-login]").forEach((b) => b.addEventListener("click", openAuth));
  $$("[data-demo-login]").forEach((b) => b.addEventListener("click", () => loginDemo(b.dataset.demoLogin)));
  $("#authSubmit").addEventListener("click", login);
  $("#createAccountBtn").addEventListener("click", createAccount);
  $("#charitySearch").addEventListener("input", renderCharities);
  $("#charityFilter").addEventListener("change", renderCharities);
  $("#scoreForm").addEventListener("submit", saveScore);
  $$("[data-plan]").forEach((b) => b.addEventListener("click", () => openCheckout(b.dataset.plan)));
  $("#cancelPlanBtn").addEventListener("click", cancelPlan);
  $("#memberCharityRange").addEventListener("input", () => $("#memberCharityPercent").textContent = `${$("#memberCharityRange").value}%`);
  $("#saveCharityBtn").addEventListener("click", saveCharitySettings);
  $("#donateBtn").addEventListener("click", donate);
  $("#uploadProofBtn").addEventListener("click", uploadProof);
  $$("[data-draw-mode]").forEach((b) => b.addEventListener("click", () => setDrawMode(b.dataset.drawMode)));
  $("#simulateDrawBtn").addEventListener("click", simulateDraw);
  $("#publishDrawBtn").addEventListener("click", publishDraw);
  $("#charityForm").addEventListener("submit", addCharity);
  $("#confirmCheckoutBtn").addEventListener("click", confirmCheckout);
  $("#saveUserEditBtn").addEventListener("click", saveUserEdit);
  $("#saveCharityEditBtn").addEventListener("click", saveCharityEdit);
}

function loadState() { try { return { ...structuredClone(demoData), ...JSON.parse(localStorage.getItem(STORAGE_KEY) || "{}") }; } catch { return structuredClone(demoData); } }
function persist() { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }
function currentUser() { return state.users.find((u) => u.id === state.currentUserId) || null; }
function subscribers() { return state.users.filter((u) => u.role === "subscriber"); }
function activeSubscribers() { return subscribers().filter((u) => u.subscriptionStatus === "active"); }
function addDays(date, days) { const next = new Date(date); next.setDate(next.getDate() + days); return next.toISOString().slice(0, 10); }
function money(v) { return `£${Math.round(v || 0).toLocaleString("en-GB")}`; }
function formatDate(text) { return text ? new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(text)) : "--"; }
function nextDrawDate() { const d = new Date(); return new Date(d.getFullYear(), d.getMonth() + 1, 1).toISOString().slice(0, 10); }
function poolBase() { return activeSubscribers().reduce((s, u) => s + plans[u.plan].price * 0.35, 0); }
function charityTotal() { return activeSubscribers().reduce((s, u) => s + plans[u.plan].price * (u.charityPercent / 100), 0); }
function poolTiers() { const b = poolBase(); return { five: b * 0.4 + state.jackpotRollover, four: b * 0.35, three: b * 0.25 }; }
function escapeHtml(v) { return String(v).replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" }[c])); }

function render() { renderAuth(); renderHeroStats(); renderCharities(); renderDraws(); renderMember(); renderAdmin(); }
function renderAuth() { const u = currentUser(); $("#loginBtn").textContent = u ? u.name.split(" ")[0] : "Login"; $("#subscribeBtn").textContent = u ? "Logout" : "Subscribe"; $("#subscribeBtn").onclick = u ? () => { state.currentUserId = null; persist(); toast("Logged out"); render(); } : openAuth; }
function renderHeroStats() { const t = poolTiers(); $("#heroPrizePool").textContent = money(t.five + t.four + t.three); $("#heroCharityTotal").textContent = money(charityTotal()); $("#heroNextDraw").textContent = formatDate(nextDrawDate()); }
function renderCharities() { const q = $("#charitySearch").value.trim().toLowerCase(); const f = $("#charityFilter").value; const list = state.charities.filter((c) => [c.name, c.description, c.event, c.cause].join(" ").toLowerCase().includes(q) && (f === "all" || c.cause === f)); $("#charityGrid").innerHTML = list.map((c) => `<article class="charity-card"><div class="charity-visual"></div><div class="charity-body"><span class="tag">${escapeHtml(c.cause)}</span><h3>${escapeHtml(c.name)}</h3><p>${escapeHtml(c.description)}</p><strong>${escapeHtml(c.event)}</strong></div></article>`).join(""); }
function renderDraws() { const t = poolTiers(); $("#tier5").textContent = money(t.five); $("#tier4").textContent = money(t.four); $("#tier3").textContent = money(t.three); const latest = state.draws.at(-1); $("#latestNumbers").textContent = latest ? latest.numbers.join("  ") : "-- -- -- -- --"; $("#latestDrawMeta").textContent = latest ? `${formatDate(latest.date)} official ${latest.mode} draw with ${latest.winners.length} winner records.` : "No official draw published yet."; }

function renderMember() { const u = currentUser(); const ok = u?.role === "subscriber"; $("#memberLoggedOut").classList.toggle("hidden", ok); $("#memberDashboard").classList.toggle("hidden", !ok); if (!ok) return; $("#subscriptionStatus").textContent = u.subscriptionStatus; $("#subscriptionStatus").className = `status-pill ${u.subscriptionStatus}`; $("#memberPlan").textContent = plans[u.plan].label; $("#memberRenewal").textContent = u.subscriptionStatus === "active" ? formatDate(u.renewalDate) : "--"; $("#memberDraws").textContent = u.drawsEntered; $("#memberWon").textContent = money(u.totalWon); const invoice = state.invoices.filter((i) => i.userId === u.id).at(-1); $("#memberInvoice").innerHTML = invoice ? `<span>Latest invoice</span><strong>${invoice.id}</strong><span>${money(invoice.amount)} · ${formatDate(invoice.date)} · ${invoice.status}</span>` : `<span>No checkout record yet</span><strong>Simulation ready</strong><span>Select a plan to generate one.</span>`; $("#memberCharityPercent").textContent = `${u.charityPercent}%`; $("#memberCharityRange").value = u.charityPercent; $("#memberCharity").innerHTML = state.charities.map((c) => `<option value="${c.id}">${escapeHtml(c.name)}</option>`).join(""); $("#memberCharity").value = u.charityId; $("#proofStatus").textContent = u.proofStatus || "pending"; $("#proofStatus").className = `status-pill ${u.proofStatus || "pending"}`; renderScores(u); $("#memberActivity").innerHTML = (u.activity || []).slice(-5).reverse().map((a) => `<div class="activity-item"><span>${escapeHtml(a)}</span></div>`).join(""); }
function renderScores(u) { $("#scoreList").innerHTML = [...u.scores].sort((a, b) => b.date.localeCompare(a.date)).map((s) => `<div class="score-item"><span>${formatDate(s.date)}</span><strong>${s.value}</strong><div class="score-actions"><button data-edit-score="${s.date}">Edit</button><button data-delete-score="${s.date}">Delete</button></div></div>`).join(""); $$('[data-edit-score]').forEach((b) => b.onclick = () => startScoreEdit(b.dataset.editScore)); $$('[data-delete-score]').forEach((b) => b.onclick = () => deleteScore(b.dataset.deleteScore)); }

function renderAdmin() { const u = currentUser(); const ok = u?.role === "admin"; $("#adminLoggedOut").classList.toggle("hidden", ok); $("#adminDashboard").classList.toggle("hidden", !ok); if (!ok) return; $("#adminUsers").textContent = subscribers().length; $("#adminActive").textContent = activeSubscribers().length; $("#adminPool").textContent = money(Object.values(poolTiers()).reduce((s, v) => s + v, 0)); $("#adminCharity").textContent = money(charityTotal()); $("#drawModeLabel").textContent = state.drawMode; $$('[data-draw-mode]').forEach((b) => b.classList.toggle("active", b.dataset.drawMode === state.drawMode)); $("#adminUserRows").innerHTML = subscribers().map((s) => { const c = state.charities.find((x) => x.id === s.charityId); return `<tr><td>${escapeHtml(s.name)}</td><td>${escapeHtml(s.email)}</td><td>${s.subscriptionStatus} / ${plans[s.plan].label}</td><td>${s.scores.length} latest</td><td>${escapeHtml(c?.name || "None")} (${s.charityPercent}%)</td><td><button class="secondary-button" data-edit-user="${s.id}">Edit</button></td></tr>`; }).join(""); $$('[data-edit-user]').forEach((b) => b.onclick = () => openUserEdit(b.dataset.editUser)); $("#winnerList").innerHTML = state.winners.length ? state.winners.map((w) => { const wu = state.users.find((x) => x.id === w.userId); return `<div class="activity-item"><span>${escapeHtml(wu?.name || "Unknown")} · ${w.tier} · ${money(w.amount)}</span><span><button class="secondary-button" data-approve-winner="${w.id}">Approve</button><button class="ghost-button" data-pay-winner="${w.id}">Paid</button></span></div>`; }).join("") : `<div class="activity-item"><span>No winners yet</span></div>`; $$('[data-approve-winner]').forEach((b) => b.onclick = () => approveWinner(b.dataset.approveWinner)); $$('[data-pay-winner]').forEach((b) => b.onclick = () => payWinner(b.dataset.payWinner)); $("#drawHistory").innerHTML = state.draws.length ? [...state.draws].reverse().map((d) => `<div class="activity-item"><span>${formatDate(d.date)} · ${d.mode} · ${d.numbers.join(" ")}</span><strong>${d.winners.length} winners</strong></div>`).join("") : `<div class="activity-item"><span>No published draws yet</span></div>`; $("#adminCharities").innerHTML = state.charities.map((c) => `<div class="activity-item"><span>${escapeHtml(c.name)} · ${escapeHtml(c.cause)}</span><span><button class="secondary-button" data-edit-charity="${c.id}">Edit</button><button class="ghost-button" data-delete-charity="${c.id}">Delete</button></span></div>`).join(""); $$('[data-edit-charity]').forEach((b) => b.onclick = () => openCharityEdit(b.dataset.editCharity)); $$('[data-delete-charity]').forEach((b) => b.onclick = () => deleteCharity(b.dataset.deleteCharity)); }

function openAuth() { $("#authDialog").showModal(); }
function loginDemo(type) { const u = type === "admin" ? state.users.find((x) => x.role === "admin") : state.users.find((x) => x.role === "subscriber"); state.currentUserId = u.id; persist(); $("#authDialog").close(); toast(`${u.name} logged in`); render(); location.hash = u.role === "admin" ? "#admin" : "#dashboard"; }
function login() { const email = $("#authEmail").value.trim().toLowerCase(); const pass = $("#authPassword").value; const u = state.users.find((x) => x.email.toLowerCase() === email && x.password === pass); if (!u) return $("#authError").textContent = "Invalid credentials. Try demo buttons."; state.currentUserId = u.id; persist(); $("#authDialog").close(); render(); location.hash = u.role === "admin" ? "#admin" : "#dashboard"; }
function createAccount() { const email = $("#authEmail").value.trim().toLowerCase(); if (!email.includes("@")) return $("#authError").textContent = "Enter a valid email."; if (state.users.some((u) => u.email.toLowerCase() === email)) return $("#authError").textContent = "This email already exists."; const id = `u${Date.now()}`; state.users.push({ id, role: "subscriber", name: email.split("@")[0].replace(/[._-]/g, " "), email, password: $("#authPassword").value || "member123", plan: "monthly", subscriptionStatus: "active", renewalDate: addDays(new Date(), 30), charityId: state.charities[0].id, charityPercent: 10, totalWon: 0, payoutStatus: "pending", proofStatus: "pending", drawsEntered: 0, scores: [], activity: ["Account created", "Subscription activated"] }); state.invoices.push(makeInvoice(id, "monthly")); state.currentUserId = id; persist(); $("#authDialog").close(); render(); location.hash = "#dashboard"; }

function openCheckout(plan) { const u = currentUser(); if (!u || u.role !== "subscriber") return openAuth(); checkoutPlan = plan; const price = plans[plan].price; $("#checkoutPlan").textContent = plans[plan].label; $("#checkoutPrice").textContent = money(price); $("#checkoutCharity").textContent = money(price * (u.charityPercent / 100)); $("#checkoutPool").textContent = money(price * 0.35); $("#checkoutDialog").showModal(); }
function confirmCheckout() { const u = currentUser(); const card = $("#cardNumber").value.replace(/\s/g, ""); if (!/^\d{12,19}$/.test(card)) return $("#checkoutError").textContent = "Enter a valid test card number."; u.plan = checkoutPlan; u.subscriptionStatus = "active"; u.renewalDate = addDays(new Date(), plans[checkoutPlan].renewalDays); state.invoices.push(makeInvoice(u.id, checkoutPlan)); u.activity.push(`Checkout completed with test card ending ${card.slice(-4)}`); persist(); $("#checkoutDialog").close(); toast("Checkout successful"); render(); }
function makeInvoice(userId, plan) { const u = state.users.find((x) => x.id === userId); const amount = plans[plan].price; return { id: `INV-${String(state.invoices.length + 1).padStart(4, "0")}`, userId, plan, amount, charityAmount: Math.round(amount * ((u?.charityPercent || 10) / 100)), poolAmount: Math.round(amount * 0.35), status: "paid", date: new Date().toISOString().slice(0, 10) }; }
function cancelPlan() { const u = currentUser(); u.subscriptionStatus = "inactive"; u.activity.push("Subscription cancelled"); persist(); render(); }

function saveScore(e) { e.preventDefault(); const u = currentUser(); const date = $("#scoreDate").value; const value = Number($("#scoreValue").value); $("#scoreError").textContent = ""; if (value < 1 || value > 45) return $("#scoreError").textContent = "Stableford score must be between 1 and 45."; if (u.scores.some((s) => s.date === date && s.date !== editingScoreDate)) return $("#scoreError").textContent = "Only one score entry is allowed per date."; if (editingScoreDate) u.scores = u.scores.filter((s) => s.date !== editingScoreDate); u.scores.push({ date, value }); u.scores = u.scores.sort((a, b) => b.date.localeCompare(a.date)).slice(0, 5); u.activity.push(`Score saved for ${formatDate(date)}`); editingScoreDate = null; $("#scoreForm").reset(); persist(); render(); }
function startScoreEdit(date) { const u = currentUser(); const s = u.scores.find((x) => x.date === date); editingScoreDate = date; $("#scoreDate").value = s.date; $("#scoreValue").value = s.value; $("#scoreError").textContent = "Editing existing score entry."; }
function deleteScore(date) { const u = currentUser(); u.scores = u.scores.filter((s) => s.date !== date); u.activity.push(`Score deleted for ${formatDate(date)}`); persist(); render(); }
function saveCharitySettings() { const u = currentUser(); u.charityId = $("#memberCharity").value; u.charityPercent = Number($("#memberCharityRange").value); u.activity.push(`Charity contribution updated to ${u.charityPercent}%`); persist(); render(); }
function donate() { const u = currentUser(); u.activity.push("Independent donation recorded"); state.notifications.push({ type: "donation", message: `${u.name} made an independent donation` }); persist(); render(); }
function uploadProof() { const u = currentUser(); if (!$("#proofUpload").files.length) return toast("Choose a proof file first"); u.proofStatus = "pending"; u.activity.push("Winner proof uploaded for admin review"); persist(); render(); }

function setDrawMode(mode) { state.drawMode = mode; persist(); render(); }
function simulateDraw() { lastSimulation = buildDraw(state.drawMode); $("#drawPreview").innerHTML = drawSummary(lastSimulation, "Simulation"); toast("Simulation ready"); }
function publishDraw() { const draw = lastSimulation || buildDraw(state.drawMode); draw.id = `d${Date.now()}`; draw.date = new Date().toISOString().slice(0, 10); draw.published = true; state.draws.push(draw); state.winners.push(...draw.winners); state.jackpotRollover = draw.winners.some((w) => w.tier === "5-match") ? 0 : poolTiers().five; draw.winners.forEach((w) => { const u = state.users.find((x) => x.id === w.userId); if (u) { u.totalWon += w.amount; u.payoutStatus = "pending"; u.proofStatus = "pending"; u.activity.push(`${w.tier} winner alert sent`); } }); activeSubscribers().forEach((u) => u.drawsEntered += 1); lastSimulation = null; persist(); $("#drawPreview").innerHTML = drawSummary(draw, "Published"); render(); }
function buildDraw(mode) { const numbers = mode === "weighted" ? weightedNumbers() : randomNumbers(); const tiers = poolTiers(); const winners = []; const counts = { "5-match": 0, "4-match": 0, "3-match": 0 }; activeSubscribers().forEach((u) => { const vals = u.scores.map((s) => s.value); const m = numbers.filter((n) => vals.includes(n)).length; if (m >= 5) counts["5-match"]++; else if (m === 4) counts["4-match"]++; else if (m === 3) counts["3-match"]++; }); activeSubscribers().forEach((u) => { const vals = u.scores.map((s) => s.value); const m = numbers.filter((n) => vals.includes(n)).length; if (m >= 5) winners.push(makeWinner(u.id, "5-match", tiers.five / counts["5-match"])); else if (m === 4) winners.push(makeWinner(u.id, "4-match", tiers.four / counts["4-match"])); else if (m === 3) winners.push(makeWinner(u.id, "3-match", tiers.three / counts["3-match"])); }); return { mode, numbers, winners, published: false }; }
function makeWinner(userId, tier, amount) { return { id: `w${Date.now()}${Math.random().toString(16).slice(2)}`, userId, tier, amount: Math.round(amount || 0), proofStatus: "pending", paymentStatus: "pending" }; }
function randomNumbers() { const set = new Set(); while (set.size < 5) set.add(Math.floor(Math.random() * 45) + 1); return [...set].sort((a, b) => a - b); }
function weightedNumbers() { const f = new Map(); activeSubscribers().forEach((u) => u.scores.forEach((s) => f.set(s.value, (f.get(s.value) || 0) + 1))); const nums = [...new Set([...f.entries()].sort((a, b) => b[1] - a[1]).map(([v]) => v))].slice(0, 5); while (nums.length < 5) { const n = Math.floor(Math.random() * 45) + 1; if (!nums.includes(n)) nums.push(n); } return nums.sort((a, b) => a - b); }
function drawSummary(draw, label) { const text = draw.winners.length ? draw.winners.map((w) => `${state.users.find((u) => u.id === w.userId)?.name || "Unknown"} ${w.tier} ${money(w.amount)}`).join("<br>") : "No winners. 5-match jackpot rolls over if published."; return `<div class="activity-item"><span>${label}: ${draw.numbers.join(" · ")}</span></div><div class="activity-item"><span>${text}</span></div>`; }
function approveWinner(id) { const w = state.winners.find((x) => x.id === id); if (!w) return; w.proofStatus = "approved"; const u = state.users.find((x) => x.id === w.userId); if (u) { u.proofStatus = "approved"; u.activity.push("Winner proof approved by admin"); } persist(); render(); }
function payWinner(id) { const w = state.winners.find((x) => x.id === id); if (!w) return; w.paymentStatus = "paid"; const u = state.users.find((x) => x.id === w.userId); if (u) { u.payoutStatus = "paid"; u.activity.push("Payout marked as paid"); } persist(); render(); }

function openUserEdit(id) { const u = state.users.find((x) => x.id === id); const latest = [...u.scores].sort((a, b) => b.date.localeCompare(a.date))[0]; $("#editUserId").value = u.id; $("#editUserName").value = u.name; $("#editUserStatus").value = u.subscriptionStatus; $("#editUserPlan").value = u.plan; $("#editUserScoreDate").value = latest?.date || ""; $("#editUserScoreValue").value = latest?.value || ""; $("#userEditDialog").showModal(); }
function saveUserEdit() { const u = state.users.find((x) => x.id === $("#editUserId").value); const date = $("#editUserScoreDate").value; const value = Number($("#editUserScoreValue").value); if (date && (value < 1 || value > 45)) return $("#editUserError").textContent = "Score must be between 1 and 45."; u.name = $("#editUserName").value.trim() || u.name; u.subscriptionStatus = $("#editUserStatus").value; u.plan = $("#editUserPlan").value; if (date) { u.scores = u.scores.filter((s) => s.date !== date); u.scores.push({ date, value }); u.scores = u.scores.sort((a, b) => b.date.localeCompare(a.date)).slice(0, 5); } u.activity.push("Admin updated subscriber profile"); persist(); $("#userEditDialog").close(); render(); }
function openCharityEdit(id) { const c = state.charities.find((x) => x.id === id); $("#editCharityId").value = c.id; $("#editCharityName").value = c.name; $("#editCharityCause").value = c.cause; $("#editCharityEvent").value = c.event; $("#editCharityDescription").value = c.description; $("#charityEditDialog").showModal(); }
function saveCharityEdit() { const c = state.charities.find((x) => x.id === $("#editCharityId").value); c.name = $("#editCharityName").value.trim() || c.name; c.cause = $("#editCharityCause").value.trim().toLowerCase() || c.cause; c.event = $("#editCharityEvent").value.trim() || c.event; c.description = $("#editCharityDescription").value.trim() || c.description; persist(); $("#charityEditDialog").close(); render(); }
function addCharity(e) { e.preventDefault(); state.charities.push({ id: `c${Date.now()}`, name: $("#newCharityName").value.trim(), cause: $("#newCharityCause").value.trim().toLowerCase(), description: "New charity profile ready for admin content updates.", event: $("#newCharityEvent").value.trim() }); $("#charityForm").reset(); persist(); render(); }
function deleteCharity(id) { if (state.charities.length <= 1) return toast("At least one charity is required"); state.charities = state.charities.filter((c) => c.id !== id); state.users.forEach((u) => { if (u.charityId === id) u.charityId = state.charities[0].id; }); persist(); render(); }
function resetDemo() { localStorage.removeItem(STORAGE_KEY); state = structuredClone(demoData); lastSimulation = null; editingScoreDate = null; persist(); render(); toast("Demo data reset"); }
function toast(message) { const el = $("#toast"); el.textContent = message; el.classList.add("show"); clearTimeout(toast.timer); toast.timer = setTimeout(() => el.classList.remove("show"), 2600); }
